name: to_do
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.3.0
  package_rename: ^1.7.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  flutter_gen_runner: ^5.6.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  

flutter:

 
  uses-material-design: true

  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
